landingpage/urls.py
from django.urls import path
from .views import *

app_name = 'landingpage'

urlpatterns = [
    path('',landingpage, name='landingpage'),
    path('tambah_status/',tambah_status, name='tambah_status'),
]

profilsaya/urls.py
from django.urls import path
from .views import *

app_name = 'profilsaya'

urlpatterns = [
    path('',profilsaya, name='profilsaya'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls', namespace='landingpage')),
    path('story7/', include('profilsaya.urls', namespace='profilsaya')),
]

landingpage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    waktu = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

profilsaya/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms

class StatusForm(forms.Form):
    status = forms.CharField(max_length=300)

landingpage/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.


def landingpage(request):
    context = {
        'form': StatusForm(),
        'data': Status.objects.all()
    }
    return render(request, 'landingpage.html', context)


def tambah_status(request):
    if StatusForm(request.POST).is_valid():
        status_baru = Status.objects.create(status=request.POST['status'])
    return redirect('/')

profilsaya/views.py
from django.shortcuts import render

# Create your views here.


def profilsaya(request):
    return render(request, 'profilsaya.html')

landingpage/templates/landingpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Story 6</title>
  </head>
  <body>
      <div class="container">
            <h1 class="text-center">Hello world</h1>
            <form action="{% url 'landingpage:tambah_status' %}" method="POST" class="d-flex justify-content-center flex-column">
            <table class="table d-flex justify-content-center">
                {%csrf_token%}
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit" class="w-25 m-auto"/>
            </form>

            <table class="table table-striped text-center">
                <thead>
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Waktu</th>
                </thead>
                <tbody>
                {%for data in data%}
                <tr>
                    <td>
                        {{forloop.counter}}
                    </td>
                    <td>
                        {{  data.status  }}
                    </td>
                    <td>
                        {{ data.waktu }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

profilsaya/templates/profilsaya.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/025b3a9369.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/story7.css' %}" />
    <title>Story 7</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-custom sticky-top">
      <a class="navbar-brand w-25" href="#">
        Profil Saya
      </a>
      <div class="d-flex" style="align-items: center;">
        <p style="margin-right: 10px;" class="badge">
          <i class="fas fa-sun fa-2x"></i>
        </p>
        <label class="switch">
          <input type="checkbox" id="light-dark-switch" />
          <span class="slider round"></span>
        </label>
        <p style="margin-left: 10px;" class="badge">
          <i class="fas fa-moon fa-2x"></i>
        </p>
      </div>
    </nav>
    <div class="bg-gray">
      <div class="container">
        <div class="header-flex-wrapper">
          <div class="header-image-wrapper">
            <img src="{% static 'images/rey.png' %}" alt="" />
          </div>
          <div class="text">
            <h1>Reynard Adha Ryanda</h1>
            <p class="subtitle">Mereka panggil saya Rey</p>
            <p>
              Halo! Saya adalah salah satu pejuang bangsa yang lahir pada
              tanggal
              <span class="red-font">16 Maret 2000</span>. Maksud saya pejuang
              bangsa adalah saya mahasiswa di
              <span class="red-font">Universitas Indonesia</span>, universitas
              yang sering dipanggil masyarakat luas sebagai universitas
              perjuangan. Saya sekarang sedang belajar
              <span class="red-font">Sistem Informasi</span> di
              <span class="red-font">Fakultas Ilmu</span>
              Komputer. Setelah liburan semester dua, saya lumayan
              <span class="red-font">tertarik dengan web development.</span>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="lead-text">
      <h1>FAQ</h1>
      <div class="red-line"></div>
    </div>

    <div class="container faq-container">
      <div class="title-container" id="aktivitas">
        <p>
          <b>Apa aktivitas yang sering kamu lakukan di waktu luang?</b>
        </p>
        <p><i class="fas fa-sort-down"></i></p>
      </div>
      <div class="desc">
        <p>
          Saya sebenarnya suka tertarik di dua hal yang berbeda, yaitu ngoding
          dan marketing. akan tetapi untuk saat ini, saya sedang mencari buku
          buat marketing tapi tidak ketemu-ketemu yang bagus (jika kalian ada
          saran, bisa langsung chat saya ya!), jadinya saya mencoba belajar
          segala sesuatu berbau ngoding yang saya sukai.
        </p>
        <p>
          Saya sebenarnya tidak pernah nyentuh koding sebelum kuliah, jadinya
          ngoding adalah hal baru bagi saya. Setiap saya ada waktu luang saya
          mencoba belajar ngoding. sekarang saya sedang tertarik dengan web
          development dan sedang mempelajari mengenai materi tersebut. Akan
          tetapi, hanya mencoba-coba tidak akan menghasilkan apapun. Jadi untuk
          saat ini saya sedang mempelajari web development segiat mungkin agar
          saya dapat diterima di sebuah organisasi yang berhubungan dengan
          teknologi dan terpusat di Fasilkom, yaitu RISTEK.
        </p>
      </div>
      <div class="title-container" id="organisasi-atau-kepanitiaan">
        <p><b>Apa pengalaman organisasi atau kepantiaan yang kamu ikuti?</b></p>
        <p><i class="fas fa-sort-down"></i></p>
      </div>
      <div class="desc">
        <p>
          Saat semester 1, saya menjadi staff di kepanitiaan Open House Fasilkom
          2018 sebagai staff HumPub. Disini saya belajar berpresentasi dan
          menjadi Master of Ceremonies di depan orang banyak. Sebenarnya bukan
          pekerjaan yang sulit, hanya saja ini kepanitiaan pertama saya yang
          bukan Dokum karena dulu saat SMA saya hanya masuk panitia jika ada
          divisi dokum. selanjutnya saya menjadi staff acara di kepantiaan BETIS
          Fasilkom 2018 (Bimbingan Belajar Gratis). Disini saya belajar
          bertanggung jawab dan mengatur sebuah acara. Acara yang saya harus
          atur berupa grand launching dan grand closing.
        </p>

        <p>
          Masuk semester 2, saya masuk ke organisasi DPM Fasilkom sebagai staff
          divisi pengawasan 1, yaitu sebuah divisi yang mengawasi BEM Fasilkom.
          Saya diberi tanggung jawab berupa mengawasi salah satu departmen di
          BEM, yaitu departmen minat dan bakat. Selanjutnya saya mengikuti CGT
          2019 sebagai Games & Competition. Saya bertanggung jawab akan
          kompetisi DoTA 2 bersama rekan-rekan saya. Kerja saya berupa mengawasi
          dan casting setiap match. Terakhir saya mengikuti kepanitiaan terbesar
          di Fasilkom saat itu, yaitu COMPFEST. Di COMPFEST, saya diterima
          sebagai staff DRM (Direct Marketing). Saya diterima karena pengalaman
          saya sebagai Master of Ceremonies di beberapa kepanitiaan lainnya.
          Disini saya mulai tertarik marketing, karena kerja DRM berupa menarik
          perhatian masyarakat supaya mereka datang ke COMPFEST dengan cara
          offline marketing.
        </p>

        <p>
          Untuk saat ini, saya diterima sebagai mentor di kepanitiaan PMB
          Fasilkom 2019. Tugasnya tidak terlalu berat karena kerja saya adalah
          mengatur dan memberi ajaran mengenai Fasilkom kepada sebelas anak yang
          saya pilih sebagai mentee. Selanjutnya merupakan kepanitiaan Open
          House Fasilkom 2019 diaman saya diamanahkan sebagai PJ Liaison
          Officer. Kerja saya berupa menangani mobilisasi dan acara Tour de
          Campus Open House Fasilkom 2019.
        </p>

        <p>
          Untuk masa yang akan datang, saya akan menerima beberapa tawaran PJ
          lainnya seperti PJ Games & Competition di Pekan Rakyat Fasilkom 2019,
          PJ Jobfair EduCare 2019, dan saya akan mencoba masuk RISTEK 2019
          sebagai staff web development.
        </p>
      </div>
      <div class="title-container" id="prestasi">
        <p><b>Apa prestasi yang kamu dapat saat masuk perkuliahan?</b></p>
        <p><i class="fas fa-sort-down"></i></p>
      </div>
      <div class="desc">
        <p>
          Dari pertama masuk kuliah sampai sekarang saya hanya baru mengikuti
          dua kompetisi dengan bidang yang sama, yaitu business plan di acara
          Arkavidia dan Festival of Agroindustry. Pada acara Arkavidia saya
          hanya sampai tahap semi-final dan kalah saat tahap presentasi. Tetapi
          hal itu tidak untuk sia-sia, karena dari pengalaman yang saya dapat
          dari Arkavidia saya berhasil meraih setidaknya juara favorit di
          Festival of Agroindustry bersama rekan-rekan saya.
        </p>
      </div>
    </div>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/story7.js' %}"></script>
  </body>
</html>